### ISSUE TITLE
test problem ?

### ISSUE THREAD

**Issue by china56321** [cardwing/Codes-for-IntRA-KD#6]
**When i run sh test_pspnet_multi_scale.sh # sh test_erfnet_multi_scale.sh,something wrong happend:** My torch version is 0.3.1 .
Traceback (most recent call last):
  File "test_pspnet_multi_scale.py", line 13, in <module>
    from models import sync_bn
  File "/home/share/make/Codes-for-IntRA-KD/models/sync_bn/__init__.py", line 1, in <module>
    from .functions.sync_bn import *
  File "/home/share/make/Codes-for-IntRA-KD/models/sync_bn/functions/__init__.py", line 1, in <module>
    from .sync_bn import *
  File "/home/share/make/Codes-for-IntRA-KD/models/sync_bn/functions/sync_bn.py", line 6, in <module>
    from .._ext import sync_bn_lib
  File "/home/share/make/Codes-for-IntRA-KD/models/sync_bn/_ext/sync_bn_lib/__init__.py", line 3, in <module>
    from ._sync_bn_lib import lib as _lib, ffi as _ffi
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

**How to solve this problem ?**

**Comment by cardwing** [comment]
You can just google the problem. It seems that the problem lies in the dependent packages.
